name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "$(date -u) — CI heartbeat" >> .github/ci-heartbeat.log
